---
abstract: 'Google Contacts Data API'
author:
  - 'Magnus Erixzon <magnus@erixzon.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102342, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Google-Contacts
requires:
  Crypt::SSLeay: 0
  File::Slurp: 0
  LWP::UserAgent: 0
  Moose: 0
  MooseX::Singleton: 0.25
  MooseX::Types: 0
  Net::Google::AuthSub: 0
  Perl6::Junction: 0
  XML::Simple: 0
resources:
  repository: http://github.com/merixzon/www-google-contacts
version: 0.18
