---
abstract: 'Google Contacts Data API'
author:
  - 'Magnus Erixzon <magnus@erixzon.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Google-Contacts
requires:
  Class::MOP: 1.09
  Crypt::SSLeay: 0
  File::Slurp: 0
  LWP::UserAgent: 0
  Moose: 0
  MooseX::Role::Parameterized: 0
  MooseX::Types: 0
  Net::Google::AuthSub: 0
  Perl6::Junction: 0
  Try::Tiny: 0
  XML::Simple: 0
resources:
  repository: git://github.com/merixzon/www-google-contacts.git
version: 0.38
